public enum MsgID
{
    // card
    ActionDrawCard,
    ActionRecycleCard,
    ActionDiscardCardFromDrawPile,
    ActionDiscardCardAndDrawSame,
    ActionDiscardCardAndDrawSameWithLimit,
    ActionDiscardCardAndGainGold,
    ActionCopyCard,
    ActionGainRandomDepCard,
    ActionGainRandomBadIdeaCard,
    ActionGainLastProjectCard,
    ActionGainSpecificCard,
    ActionCopyCardFromVegue,
    ActionTryToPlayHand,
    ActionAddHandLimit,
    ActionGainSpecTypeCard,
    ActionDeleteBadIdea,
    // gold
    ActionGainIncome,
    ActionDoubleGold,
    ActionGainGold,
    ActionPayGold,
    // map bonus
    ActionGainMapBonus5Gold,
    ActionGainRandomMapBonus,
    // popR
    ActionGainPopR,
    ActionGainVenuePopR,
    // time
    ActionGainTime,
    ActionPayTime,
    // workPos
    ActionTraining,
    ActionTrainingPromotionDep,
    ActionGainWorkPos,
    // worker
    ActionGainWorker,
    ActionGainTWorker,
    ActionGainSpecWorker,
    // book
    ActionGainRandomBook,
    ActionUseBook,
    ActionGainBook,
    ActionDiscardBook,
    ActionSellBook,
    // zoo land
    ActionClearRock,
    ActionClearLake,
    ActionGainMapBonus,
    // zoo
    ActionPlayAHandFreely,
    ActionBuildBigVenueFreely,
    ActionBuildMonkeyVenue,
    ActionDemolitionVenueWithCost,
    ActionExpand,
    ActionExpandRandomly,
    ActionExpandFreely,
    ActionDemolitionVenue,
    // shop
    ActionGoShop,
    ActionBuyBook,
    ActionBuyCard,
    ActionDiscardCardInShop,
    // internal msg
    ResolveEventChoiceEffect,
    ResolveCardEffect,
    ResolveWorkPosEffect,
    ResolveEndSeason,
    ResolveStartSeason,
    ResolveNextEvent,
    UseWorker,
    AddVenue,
    RemoveVenue,
    DiscardACard,
    GainACard,
    // used to update view
    AfterMapChanged,
    AfterBookChanged,
    AfterWorkPosChanged,
    AfterWorkerChanged,
    AfterPopRatingChanged,
    AfterGoldChanged,
    AfterTimeResChanged,
    AfterCardChanged,
    AfterShopChanged,
    // outside the game
    StartGame,
}
