public enum MsgID
{
    // card
    ActionDrawCardAndMayDiscard,
    ActionRecycleCard,
    ActionDiscardCardFromDrawPile,
    ActionDiscardCardAndDrawSame,
    ActionDiscardCardAndDrawSameWithLimit,
    ActionDiscardCardAndGainGold,
    ActionCopyCard,
    ActionGainRandomDepCard,
    ActionGainRandomBadIdeaCard,
    ActionGainLastProjectCard,
    ActionGainSpecificCard,
    ActionCopyCardFromVegue,
    ActionTryToPlayHand,
    ActionTryToPlayHandsFreely,
    ActionAddHandLimit,
    ActionGainSpecTypeCard,
    ActionDeleteBadIdeaCard,
    // buff
    ActionBuffChanged,
    // gold
    ActionGainIncome,
    ActionDoubleGold,
    ActionGainGold,
    ActionPayGold,
    // map bonus
    ActionGainMapBonus5Gold,
    ActionGainRandomMapBonus,
    // popR
    ActionGainPopR,
    ActionGainVenuePopR,
    // time
    ActionGainTime,
    ActionPayTime,
    // workPos
    ActionTraining,
    ActionTrainingPromotionDep,
    ActionGainWorkPos,
    // worker
    ActionGainWorker,
    ActionGainTWorker,
    ActionGainSpecWorker,
    // book
    ActionGainRandomBook,
    ActionUseBook,
    ActionGainBook,
    ActionDiscardBook,
    ActionSellBook,
    // zoo land
    ActionClearRock,
    ActionClearLake,
    ActionGainMapBonus,
    // zoo
    ActionPlayAHandFreely,
    ActionBuildBigVenueFreely,
    ActionBuildMonkeyVenue,
    ActionDemolitionVenueWithCost,
    ActionExpand,
    ActionExpandRandomly,
    ActionDemolitionVenue,
    // shop
    ActionGoShop,
    ActionBuyBook,
    ActionBuyCard,
    ActionDiscardCardInShop,
    ActionExitShop,
    // internal msg
    ResolveEventChoiceEffect,
    ResolveCardEffect,
    ResolveCardsEffect,
    ResolveWorkPosEffect,
    ResolveEndSeason,
    ResolveStartSeason,
    ResolveEvent,
    UseWorker,
    AddVenue,
    RemoveVenue,
    // card inner
    DiscardCard,
    CardFromDrawToHand,
    CardFromDrawToDiscard,
    CardToHand,
    CardFromHandToDiscard,
    CardFromDiscardToHand,
    DeleteCardFromHand,
    CardFromNoWhereToDiscard,
    // used to update view or trigger passive
    AfterGainCard,
    AfterMapChanged,
    AfterBookChanged,
    AfterWorkPosChanged,
    AfterWorkerChanged,
    AfterPopRatingChanged,
    AfterGoldChanged,
    AfterTimeResChanged,
    AfterCardChanged,
    AfterShopChanged,
    AfterConsoleChanged,
    AfterTurnChanged,
    AfterBuffChanged,
    AfterResolveCard,
    AfterUseWorker,
    AfterUseBook,
    OnTurnEnd,
    BeforeVenueTakeEffect,
    AfterVenueTakeEffect,
    AfterGainMapBonues,
    AfterGainACard,
    AfterGainPopRByVenue,
    AfterExpand,
    AfterDemolition,
    AfterStatisticChange,
    AfterHandLimitChange,
    AfterViewDetailChange,
    AfterTurnStepChanged,
    // outside the game
    StartGame,
    // Console
    ConsoleMsg,
    // Ani
    VenueTakeEffectAni,
}
