public enum MsgID
{
    // card
    ActionDrawCardAndMayDiscard,
    ActionRecycleCard,
    ActionDiscardCardFromDrawPile,
    ActionDiscardCardAndDrawSame,
    ActionDiscardCardAndDrawSameWithLimit,
    ActionDiscardCardAndGainCoin,
    ActionCopyCard,
    ActionGainRandomActionSpaceCard,
    ActionGainRandomBadIdeaCard,
    ActionGainLastProjectCard,
    ActionGainSpecificCard,
    ActionCopyCardFromVegue,
    ActionTryToPlayHand,
    ActionTryToPlayHandsFreely,
    ActionAddHandLimit,
    ActionGainSpecTypeCard,
    ActionDeleteBadIdeaCard,
    // buff
    ActionBuffChanged,
    // coin
    ActionGainIncome,
    ActionDoubleCoin,
    ActionGainCoin,
    ActionPayCoin,
    // plot reward
    ActionGainPlotReward5Coin,
    ActionGainRandomPlotReward,
    // popularity
    ActionGainPopularity,
    ActionGainExhibitPopularity,
    // time
    ActionGainTime,
    ActionPayTime,
    // action space
    ActionTraining,
    ActionTrainingPromotionDep,
    ActionGainActionSpace,
    // worker
    ActionGainWorker,
    ActionGainTWorker,
    ActionGainSpecWorker,
    // book
    ActionGainRandomBook,
    ActionUseBook,
    ActionGainBook,
    ActionDiscardBook,
    ActionSellBook,
    // zoo land
    ActionClearRock,
    ActionClearLake,
    ActionGainPlotReward,
    // zoo
    ActionPlayAHandFreely,
    ActionBuildBigExhibitFreely,
    ActionBuildMonkeyExhibit,
    ActionDemolitionExhibitWithCost,
    ActionExpand,
    ActionExpandRandomly,
    ActionDemolitionExhibit,
    // shop
    ActionGoShop,
    ActionBuyBook,
    ActionBuyCard,
    ActionDiscardCardInShop,
    ActionExitShop,
    // internal msg
    ResolveEventChoiceEffect,
    ResolveCardEffect,
    ResolveCardsEffect,
    ResolveActionSpaceEffect,
    ResolveEndSeason,
    ResolveStartSeason,
    ResolveEvent,
    UseWorker,
    AddExhibit,
    RemoveExhibit,
    // card inner
    DiscardCard,
    CardFromDrawToHand,
    CardFromDrawToDiscard,
    CardToHand,
    CardFromHandToDiscard,
    CardFromDiscardToHand,
    DeleteCardFromHand,
    CardFromNoWhereToDiscard,
    // used to update view or trigger passive
    AfterGainCard,
    AfterPlotChanged,
    AfterBookChanged,
    AfterActionSpaceChanged,
    AfterWorkerChanged,
    AfterPopularityChanged,
    AfterCoinChanged,
    AfterTimeResChanged,
    AfterCardChanged,
    AfterShopChanged,
    AfterConsoleChanged,
    AfterTurnChanged,
    AfterBuffChanged,
    AfterResolveCard,
    AfterUseWorker,
    AfterUseBook,
    OnTurnEnd,
    BeforeExhibitTakeEffect,
    AfterExhibitTakeEffect,
    AfterGainPlotReward,
    AfterGainACard,
    AfterGainPopularityByExhibit,
    AfterExpand,
    AfterDemolition,
    AfterStatisticChange,
    AfterHandLimitChange,
    AfterViewDetailChange,
    AfterTurnStepChanged,
    // outside the game
    StartGame,
    // Console
    ConsoleMsg,
    // Ani
    ExhibitTakeEffectAni,
}
